name: build

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: latest

            - name: Build
              run: |
                npm ci
                npm run bundle
                npm run bundle-min

            - name: Lint
              run: |
                npm run commitlint
                npm run lint

            - name: Test
              run: |
                npm test